In [1]:
from pathlib import Path
import pandas as pd
import spacy

In [2]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\balda\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\balda\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: C:\Users\balda\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
!python -m spacy download en_core_web_lg
!python -m spacy download fr_core_news_lg
!python -m spacy download nl_core_news_lg

Collecting en-core-web-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl (400.7 MB)
     ---------------------------------------- 0.0/400.7 MB ? eta -:--:--
     --------------------------------------- 2.9/400.7 MB 16.7 MB/s eta 0:00:24
      -------------------------------------- 6.0/400.7 MB 15.4 MB/s eta 0:00:26
      ------------------------------------- 10.2/400.7 MB 16.8 MB/s eta 0:00:24
     - ------------------------------------ 12.6/400.7 MB 15.8 MB/s eta 0:00:25
     - ------------------------------------ 15.2/400.7 MB 14.9 MB/s eta 0:00:26
     - ------------------------------------ 18.4/400.7 MB 15.0 MB/s eta 0:00:26
     -- ----------------------------------- 21.5/400.7 MB 15.1 MB/s eta 0:00:26
     -- ----------------------------------- 24.4/400.7 MB 15.0 MB/s eta 0:00:26
     -- ----------------------------------- 26.7/400.7 MB 14.5 MB/s eta 0:00:26
     -- ----------------------------------- 29.6/400.7 MB 14.4 MB/s eta 0:00:26
     --- ---------------------------------- 32.8/400.7 MB 14.4 MB/s eta 0:00:26
     --- ---------------------------------- 36.4/400.7 MB 14.7 MB/s eta 0:00:25
     --- ---------------------------------- 39.6/400.7 MB 14.8 MB/s eta 0:00:25
     ---- --------------------------------- 43.3/400.7 MB 14.9 MB/s eta 0:00:25
     ---- --------------------------------- 46.9/400.7 MB 15.0 MB/s eta 0:00:24
     ---- --------------------------------- 50.3/400.7 MB 15.2 MB/s eta 0:00:24
     ----- -------------------------------- 53.7/400.7 MB 15.2 MB/s eta 0:00:23
     ----- -------------------------------- 57.4/400.7 MB 15.4 MB/s eta 0:00:23
     ----- -------------------------------- 61.1/400.7 MB 15.4 MB/s eta 0:00:22
     ------ ------------------------------- 64.5/400.7 MB 15.4 MB/s eta 0:00:22
     ------ ------------------------------- 67.6/400.7 MB 15.5 MB/s eta 0:00:22
     ------ ------------------------------- 71.6/400.7 MB 15.6 MB/s eta 0:00:22
     ------- ------------------------------ 75.0/400.7 MB 15.6 MB/s eta 0:00:21
     ------- ------------------------------ 78.4/400.7 MB 15.6 MB/s eta 0:00:21
     ------- ------------------------------ 82.1/400.7 MB 15.7 MB/s eta 0:00:21
     -------- ----------------------------- 85.7/400.7 MB 15.8 MB/s eta 0:00:20
     -------- ----------------------------- 89.4/400.7 MB 15.8 MB/s eta 0:00:20
     -------- ----------------------------- 93.3/400.7 MB 15.9 MB/s eta 0:00:20
     --------- ---------------------------- 97.0/400.7 MB 16.0 MB/s eta 0:00:20
     --------- --------------------------- 100.4/400.7 MB 16.0 MB/s eta 0:00:19
     --------- --------------------------- 104.3/400.7 MB 16.1 MB/s eta 0:00:19
     --------- --------------------------- 108.3/400.7 MB 16.1 MB/s eta 0:00:19
     ---------- -------------------------- 111.9/400.7 MB 16.2 MB/s eta 0:00:18
     ---------- -------------------------- 115.9/400.7 MB 16.3 MB/s eta 0:00:18
     ----------- ------------------------- 119.8/400.7 MB 16.3 MB/s eta 0:00:18
     ----------- ------------------------- 123.5/400.7 MB 16.4 MB/s eta 0:00:17
     ----------- ------------------------- 127.1/400.7 MB 16.4 MB/s eta 0:00:17
     ------------ ------------------------ 130.8/400.7 MB 16.4 MB/s eta 0:00:17
     ------------ ------------------------ 134.5/400.7 MB 16.5 MB/s eta 0:00:17
     ------------ ------------------------ 138.4/400.7 MB 16.5 MB/s eta 0:00:16
     ------------- ----------------------- 142.1/400.7 MB 16.6 MB/s eta 0:00:16
     ------------- ----------------------- 145.8/400.7 MB 16.6 MB/s eta 0:00:16
     ------------- ----------------------- 149.7/400.7 MB 16.6 MB/s eta 0:00:16
     -------------- ---------------------- 153.4/400.7 MB 16.7 MB/s eta 0:00:15
     -------------- ---------------------- 157.3/400.7 MB 16.7 MB/s eta 0:00:15
     -------------- ---------------------- 161.0/400.7 MB 16.7 MB/s eta 0:00:15
     --------------- --------------------- 164.9/400.7 MB 16.8 MB/s eta 0:00:15
     --------------- --------------------- 168.6/400.7 MB 16.8 MB/s eta 0:00:14
     --------------- --------------------- 172.2/400.7 MB 16.8 MB/s eta 0:00:14
     ---------------- -------------------- 175.9/400.7 MB 16.8 MB/s eta 0:00:14
     ---------------- -------------------- 179.6/400.7 MB 16.8 MB/s eta 0:00:14
     ---------------- -------------------- 183.2/400.7 MB 16.8 MB/s eta 0:00:13
     ----------------- ------------------- 186.9/400.7 MB 16.8 MB/s eta 0:00:13
     ----------------- ------------------- 190.8/400.7 MB 16.9 MB/s eta 0:00:13
     ----------------- ------------------- 194.5/400.7 MB 16.9 MB/s eta 0:00:13
     ------------------ ------------------ 198.4/400.7 MB 16.9 MB/s eta 0:00:12
     ------------------ ------------------ 202.4/400.7 MB 16.9 MB/s eta 0:00:12
     ------------------- ----------------- 206.0/400.7 MB 16.9 MB/s eta 0:00:12
     ------------------- ----------------- 209.7/400.7 MB 17.0 MB/s eta 0:00:12
     ------------------- ----------------- 213.6/400.7 MB 17.0 MB/s eta 0:00:12
     -------------------- ---------------- 217.6/400.7 MB 17.0 MB/s eta 0:00:11
     -------------------- ---------------- 221.0/400.7 MB 17.0 MB/s eta 0:00:11
     -------------------- ---------------- 224.7/400.7 MB 17.0 MB/s eta 0:00:11
     --------------------- --------------- 228.3/400.7 MB 17.0 MB/s eta 0:00:11
     --------------------- --------------- 231.5/400.7 MB 17.0 MB/s eta 0:00:10
     --------------------- --------------- 235.4/400.7 MB 17.0 MB/s eta 0:00:10
     ---------------------- -------------- 239.1/400.7 MB 17.0 MB/s eta 0:00:10
     ---------------------- -------------- 243.0/400.7 MB 17.0 MB/s eta 0:00:10
     ---------------------- -------------- 246.9/400.7 MB 17.0 MB/s eta 0:00:10
     ----------------------- ------------- 250.6/400.7 MB 17.1 MB/s eta 0:00:09
     ----------------------- ------------- 254.5/400.7 MB 17.1 MB/s eta 0:00:09
     ----------------------- ------------- 258.2/400.7 MB 17.1 MB/s eta 0:00:09
     ------------------------ ------------ 261.9/400.7 MB 17.1 MB/s eta 0:00:09
     ------------------------ ------------ 265.8/400.7 MB 17.1 MB/s eta 0:00:08
     ------------------------ ------------ 269.5/400.7 MB 17.1 MB/s eta 0:00:08
     ------------------------- ----------- 273.4/400.7 MB 17.2 MB/s eta 0:00:08
     ------------------------- ----------- 277.1/400.7 MB 17.3 MB/s eta 0:00:08
     ------------------------- ----------- 280.5/400.7 MB 17.3 MB/s eta 0:00:07
     -------------------------- ---------- 284.2/400.7 MB 17.4 MB/s eta 0:00:07
     -------------------------- ---------- 288.1/400.7 MB 17.5 MB/s eta 0:00:07
     -------------------------- ---------- 292.0/400.7 MB 17.6 MB/s eta 0:00:07
     --------------------------- --------- 295.7/400.7 MB 17.6 MB/s eta 0:00:06
     --------------------------- --------- 299.4/400.7 MB 17.6 MB/s eta 0:00:06
     ---------------------------- -------- 303.3/400.7 MB 17.7 MB/s eta 0:00:06
     ---------------------------- -------- 307.0/400.7 MB 17.7 MB/s eta 0:00:06
     ---------------------------- -------- 310.6/400.7 MB 17.7 MB/s eta 0:00:06
     ----------------------------- ------- 314.6/400.7 MB 17.7 MB/s eta 0:00:05
     ----------------------------- ------- 318.5/400.7 MB 17.7 MB/s eta 0:00:05
     ----------------------------- ------- 322.2/400.7 MB 17.7 MB/s eta 0:00:05
     ------------------------------ ------ 326.1/400.7 MB 17.7 MB/s eta 0:00:05
     ------------------------------ ------ 329.8/400.7 MB 17.8 MB/s eta 0:00:04
     ------------------------------ ------ 333.4/400.7 MB 17.8 MB/s eta 0:00:04
     ------------------------------- ----- 337.4/400.7 MB 17.8 MB/s eta 0:00:04
     ------------------------------- ----- 341.0/400.7 MB 17.8 MB/s eta 0:00:04
     ------------------------------- ----- 345.0/400.7 MB 17.9 MB/s eta 0:00:04
     -------------------------------- ---- 348.7/400.7 MB 17.9 MB/s eta 0:00:03
     -------------------------------- ---- 352.3/400.7 MB 17.9 MB/s eta 0:00:03
     -------------------------------- ---- 356.3/400.7 MB 17.9 MB/s eta 0:00:03
     --------------------------------- --- 359.9/400.7 MB 17.9 MB/s eta 0:00:03
     --------------------------------- --- 363.6/400.7 MB 17.9 MB/s eta 0:00:03
     --------------------------------- --- 367.3/400.7 MB 17.9 MB/s eta 0:00:02
     ---------------------------------- -- 371.2/400.7 MB 17.9 MB/s eta 0:00:02
     ---------------------------------- -- 374.9/400.7 MB 17.9 MB/s eta 0:00:02
     ---------------------------------- -- 378.8/400.7 MB 17.9 MB/s eta 0:00:02
     ----------------------------------- - 382.5/400.7 MB 17.9 MB/s eta 0:00:02
     ----------------------------------- - 386.1/400.7 MB 17.9 MB/s eta 0:00:01
     ----------------------------------- - 389.8/400.7 MB 17.9 MB/s eta 0:00:01
     ------------------------------------  393.5/400.7 MB 17.9 MB/s eta 0:00:01
     ------------------------------------  397.4/400.7 MB 17.9 MB/s eta 0:00:01
     ------------------------------------  400.6/400.7 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  400.6/400.7 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  400.6/400.7 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  400.6/400.7 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  400.6/400.7 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  400.6/400.7 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  400.6/400.7 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  400.6/400.7 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  400.6/400.7 MB 17.8 MB/s eta 0:00:01
     ---------------------------------------- 400.7/400.7 MB 15.8 MB/s  0:00:24
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: C:\Users\balda\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Collecting fr-core-news-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/fr_core_news_lg-3.8.0/fr_core_news_lg-3.8.0-py3-none-any.whl (571.8 MB)
     ---------------------------------------- 0.0/571.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/571.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/571.8 MB ? eta -:--:--
     --------------------------------------- 2.9/571.8 MB 16.8 MB/s eta 0:00:34
     --------------------------------------- 6.0/571.8 MB 17.6 MB/s eta 0:00:33
      ------------------------------------- 10.5/571.8 MB 17.7 MB/s eta 0:00:32
      ------------------------------------- 13.9/571.8 MB 17.5 MB/s eta 0:00:32
     - ------------------------------------ 17.8/571.8 MB 17.8 MB/s eta 0:00:32
     - ------------------------------------ 21.8/571.8 MB 17.9 MB/s eta 0:00:31
     - ------------------------------------ 25.4/571.8 MB 17.7 MB/s eta 0:00:31
     - ------------------------------------ 29.4/571.8 MB 17.7 MB/s eta 0:00:31
     -- ----------------------------------- 33.3/571.8 MB 17.8 MB/s eta 0:00:31
     -- ----------------------------------- 37.0/571.8 MB 17.8 MB/s eta 0:00:31
     -- ----------------------------------- 40.9/571.8 MB 17.8 MB/s eta 0:00:30
     -- ----------------------------------- 44.6/571.8 MB 17.8 MB/s eta 0:00:30
     --- ---------------------------------- 48.2/571.8 MB 17.8 MB/s eta 0:00:30
     --- ---------------------------------- 51.9/571.8 MB 17.9 MB/s eta 0:00:30
     --- ---------------------------------- 55.8/571.8 MB 17.9 MB/s eta 0:00:29
     --- ---------------------------------- 59.5/571.8 MB 17.9 MB/s eta 0:00:29
     ---- --------------------------------- 63.2/571.8 MB 17.8 MB/s eta 0:00:29
     ---- --------------------------------- 67.1/571.8 MB 17.8 MB/s eta 0:00:29
     ---- --------------------------------- 70.8/571.8 MB 17.8 MB/s eta 0:00:29
     ---- --------------------------------- 74.4/571.8 MB 17.8 MB/s eta 0:00:28
     ----- -------------------------------- 78.1/571.8 MB 17.8 MB/s eta 0:00:28
     ----- -------------------------------- 81.3/571.8 MB 17.8 MB/s eta 0:00:28
     ----- -------------------------------- 84.9/571.8 MB 17.7 MB/s eta 0:00:28
     ----- -------------------------------- 88.1/571.8 MB 17.6 MB/s eta 0:00:28
     ------ ------------------------------- 91.2/571.8 MB 17.5 MB/s eta 0:00:28
     ------ ------------------------------- 95.2/571.8 MB 17.5 MB/s eta 0:00:28
     ------ ------------------------------- 99.1/571.8 MB 17.5 MB/s eta 0:00:27
     ------ ------------------------------ 102.8/571.8 MB 17.5 MB/s eta 0:00:27
     ------ ------------------------------ 106.4/571.8 MB 17.6 MB/s eta 0:00:27
     ------- ----------------------------- 110.1/571.8 MB 17.6 MB/s eta 0:00:27
     ------- ----------------------------- 113.8/571.8 MB 17.6 MB/s eta 0:00:27
     ------- ----------------------------- 117.4/571.8 MB 17.6 MB/s eta 0:00:26
     ------- ----------------------------- 120.8/571.8 MB 17.6 MB/s eta 0:00:26
     -------- ---------------------------- 124.0/571.8 MB 17.5 MB/s eta 0:00:26
     -------- ---------------------------- 127.1/571.8 MB 17.4 MB/s eta 0:00:26
     -------- ---------------------------- 129.5/571.8 MB 17.3 MB/s eta 0:00:26
     -------- ---------------------------- 132.1/571.8 MB 17.1 MB/s eta 0:00:26
     -------- ---------------------------- 134.7/571.8 MB 17.0 MB/s eta 0:00:26
     -------- ---------------------------- 138.4/571.8 MB 17.0 MB/s eta 0:00:26
     --------- --------------------------- 142.1/571.8 MB 17.0 MB/s eta 0:00:26
     --------- --------------------------- 145.5/571.8 MB 17.0 MB/s eta 0:00:26
     --------- --------------------------- 149.2/571.8 MB 17.0 MB/s eta 0:00:25
     --------- --------------------------- 152.8/571.8 MB 17.0 MB/s eta 0:00:25
     ---------- -------------------------- 156.2/571.8 MB 17.0 MB/s eta 0:00:25
     ---------- -------------------------- 159.6/571.8 MB 17.0 MB/s eta 0:00:25
     ---------- -------------------------- 162.8/571.8 MB 16.9 MB/s eta 0:00:25
     ---------- -------------------------- 166.2/571.8 MB 16.9 MB/s eta 0:00:25
     ---------- -------------------------- 169.9/571.8 MB 16.9 MB/s eta 0:00:24
     ----------- ------------------------- 173.0/571.8 MB 16.9 MB/s eta 0:00:24
     ----------- ------------------------- 176.2/571.8 MB 16.8 MB/s eta 0:00:24
     ----------- ------------------------- 179.8/571.8 MB 16.9 MB/s eta 0:00:24
     ----------- ------------------------- 183.8/571.8 MB 16.9 MB/s eta 0:00:23
     ------------ ------------------------ 187.4/571.8 MB 16.9 MB/s eta 0:00:23
     ------------ ------------------------ 190.8/571.8 MB 16.9 MB/s eta 0:00:23
     ------------ ------------------------ 194.5/571.8 MB 16.9 MB/s eta 0:00:23
     ------------ ------------------------ 198.4/571.8 MB 16.9 MB/s eta 0:00:23
     ------------- ----------------------- 202.4/571.8 MB 16.9 MB/s eta 0:00:22
     ------------- ----------------------- 206.0/571.8 MB 16.9 MB/s eta 0:00:22
     ------------- ----------------------- 209.7/571.8 MB 16.9 MB/s eta 0:00:22
     ------------- ----------------------- 213.6/571.8 MB 17.0 MB/s eta 0:00:22
     -------------- ---------------------- 217.3/571.8 MB 17.0 MB/s eta 0:00:21
     -------------- ---------------------- 221.0/571.8 MB 17.0 MB/s eta 0:00:21
     -------------- ---------------------- 224.9/571.8 MB 17.0 MB/s eta 0:00:21
     -------------- ---------------------- 228.9/571.8 MB 17.0 MB/s eta 0:00:21
     --------------- --------------------- 232.5/571.8 MB 17.0 MB/s eta 0:00:20
     --------------- --------------------- 236.2/571.8 MB 17.1 MB/s eta 0:00:20
     --------------- --------------------- 240.1/571.8 MB 17.1 MB/s eta 0:00:20
     --------------- --------------------- 244.1/571.8 MB 17.1 MB/s eta 0:00:20
     ---------------- -------------------- 247.7/571.8 MB 17.1 MB/s eta 0:00:19
     ---------------- -------------------- 251.7/571.8 MB 17.1 MB/s eta 0:00:19
     ---------------- -------------------- 255.6/571.8 MB 17.1 MB/s eta 0:00:19
     ---------------- -------------------- 259.3/571.8 MB 17.1 MB/s eta 0:00:19
     ----------------- ------------------- 262.9/571.8 MB 17.2 MB/s eta 0:00:19
     ----------------- ------------------- 266.6/571.8 MB 17.2 MB/s eta 0:00:18
     ----------------- ------------------- 270.3/571.8 MB 17.2 MB/s eta 0:00:18
     ----------------- ------------------- 274.2/571.8 MB 17.2 MB/s eta 0:00:18
     ----------------- ------------------- 277.9/571.8 MB 17.2 MB/s eta 0:00:18
     ------------------ ------------------ 281.0/571.8 MB 17.1 MB/s eta 0:00:17
     ------------------ ------------------ 284.4/571.8 MB 17.1 MB/s eta 0:00:17
     ------------------ ------------------ 287.8/571.8 MB 17.1 MB/s eta 0:00:17
     ------------------ ------------------ 291.8/571.8 MB 17.1 MB/s eta 0:00:17
     ------------------- ----------------- 295.2/571.8 MB 17.1 MB/s eta 0:00:17
     ------------------- ----------------- 298.8/571.8 MB 17.1 MB/s eta 0:00:16
     ------------------- ----------------- 302.5/571.8 MB 17.1 MB/s eta 0:00:16
     ------------------- ----------------- 306.7/571.8 MB 17.1 MB/s eta 0:00:16
     -------------------- ---------------- 310.4/571.8 MB 17.1 MB/s eta 0:00:16
     -------------------- ---------------- 314.0/571.8 MB 17.0 MB/s eta 0:00:16
     -------------------- ---------------- 317.7/571.8 MB 17.0 MB/s eta 0:00:15
     -------------------- ---------------- 320.3/571.8 MB 17.0 MB/s eta 0:00:15
     -------------------- ---------------- 324.0/571.8 MB 17.0 MB/s eta 0:00:15
     --------------------- --------------- 327.4/571.8 MB 17.0 MB/s eta 0:00:15
     --------------------- --------------- 330.6/571.8 MB 17.0 MB/s eta 0:00:15
     --------------------- --------------- 334.2/571.8 MB 17.0 MB/s eta 0:00:15
     --------------------- --------------- 338.2/571.8 MB 17.0 MB/s eta 0:00:14
     ---------------------- -------------- 341.8/571.8 MB 17.0 MB/s eta 0:00:14
     ---------------------- -------------- 345.5/571.8 MB 17.0 MB/s eta 0:00:14
     ---------------------- -------------- 349.4/571.8 MB 17.0 MB/s eta 0:00:14
     ---------------------- -------------- 353.1/571.8 MB 17.1 MB/s eta 0:00:13
     ----------------------- ------------- 357.0/571.8 MB 17.1 MB/s eta 0:00:13
     ----------------------- ------------- 360.7/571.8 MB 17.1 MB/s eta 0:00:13
     ----------------------- ------------- 364.4/571.8 MB 17.1 MB/s eta 0:00:13
     ----------------------- ------------- 368.1/571.8 MB 17.1 MB/s eta 0:00:12
     ------------------------ ------------ 371.7/571.8 MB 17.0 MB/s eta 0:00:12
     ------------------------ ------------ 375.4/571.8 MB 17.1 MB/s eta 0:00:12
     ------------------------ ------------ 379.1/571.8 MB 17.0 MB/s eta 0:00:12
     ------------------------ ------------ 383.0/571.8 MB 17.1 MB/s eta 0:00:12
     ------------------------- ----------- 386.9/571.8 MB 17.1 MB/s eta 0:00:11
     ------------------------- ----------- 390.6/571.8 MB 17.2 MB/s eta 0:00:11
     ------------------------- ----------- 394.5/571.8 MB 17.3 MB/s eta 0:00:11
     ------------------------- ----------- 398.2/571.8 MB 17.4 MB/s eta 0:00:10
     -------------------------- ---------- 401.9/571.8 MB 17.4 MB/s eta 0:00:10
     -------------------------- ---------- 405.8/571.8 MB 17.4 MB/s eta 0:00:10
     -------------------------- ---------- 409.5/571.8 MB 17.4 MB/s eta 0:00:10
     -------------------------- ---------- 413.4/571.8 MB 17.5 MB/s eta 0:00:10
     -------------------------- ---------- 417.1/571.8 MB 17.4 MB/s eta 0:00:09
     --------------------------- --------- 421.0/571.8 MB 17.5 MB/s eta 0:00:09
     --------------------------- --------- 424.7/571.8 MB 17.5 MB/s eta 0:00:09
     --------------------------- --------- 428.6/571.8 MB 17.6 MB/s eta 0:00:09
     --------------------------- --------- 432.3/571.8 MB 17.6 MB/s eta 0:00:08
     ---------------------------- -------- 436.2/571.8 MB 17.6 MB/s eta 0:00:08
     ---------------------------- -------- 439.9/571.8 MB 17.7 MB/s eta 0:00:08
     ---------------------------- -------- 443.8/571.8 MB 17.7 MB/s eta 0:00:08
     ---------------------------- -------- 447.7/571.8 MB 17.7 MB/s eta 0:00:08
     ----------------------------- ------- 451.7/571.8 MB 17.7 MB/s eta 0:00:07
     ----------------------------- ------- 455.3/571.8 MB 17.7 MB/s eta 0:00:07
     ----------------------------- ------- 459.0/571.8 MB 17.7 MB/s eta 0:00:07
     ----------------------------- ------- 462.7/571.8 MB 17.7 MB/s eta 0:00:07
     ------------------------------ ------ 466.4/571.8 MB 17.7 MB/s eta 0:00:06
     ------------------------------ ------ 470.3/571.8 MB 17.7 MB/s eta 0:00:06
     ------------------------------ ------ 474.0/571.8 MB 17.7 MB/s eta 0:00:06
     ------------------------------ ------ 477.9/571.8 MB 17.7 MB/s eta 0:00:06
     ------------------------------- ----- 481.6/571.8 MB 17.7 MB/s eta 0:00:06
     ------------------------------- ----- 486.3/571.8 MB 17.7 MB/s eta 0:00:05
     ------------------------------- ----- 489.7/571.8 MB 17.7 MB/s eta 0:00:05
     ------------------------------- ----- 493.4/571.8 MB 17.7 MB/s eta 0:00:05
     -------------------------------- ---- 497.0/571.8 MB 17.7 MB/s eta 0:00:05
     -------------------------------- ---- 501.0/571.8 MB 17.7 MB/s eta 0:00:05
     -------------------------------- ---- 504.4/571.8 MB 17.7 MB/s eta 0:00:04
     -------------------------------- ---- 508.0/571.8 MB 17.7 MB/s eta 0:00:04
     --------------------------------- --- 512.0/571.8 MB 17.7 MB/s eta 0:00:04
     --------------------------------- --- 515.9/571.8 MB 17.7 MB/s eta 0:00:04
     --------------------------------- --- 519.6/571.8 MB 17.7 MB/s eta 0:00:03
     --------------------------------- --- 523.5/571.8 MB 17.7 MB/s eta 0:00:03
     ---------------------------------- -- 527.2/571.8 MB 17.7 MB/s eta 0:00:03
     ---------------------------------- -- 530.8/571.8 MB 17.7 MB/s eta 0:00:03
     ---------------------------------- -- 534.5/571.8 MB 17.7 MB/s eta 0:00:03
     ---------------------------------- -- 538.4/571.8 MB 17.7 MB/s eta 0:00:02
     ----------------------------------- - 542.4/571.8 MB 17.7 MB/s eta 0:00:02
     ----------------------------------- - 546.0/571.8 MB 17.8 MB/s eta 0:00:02
     ----------------------------------- - 549.7/571.8 MB 17.8 MB/s eta 0:00:02
     ----------------------------------- - 553.4/571.8 MB 17.8 MB/s eta 0:00:02
     ------------------------------------  557.3/571.8 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  561.3/571.8 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  565.2/571.8 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  568.9/571.8 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  571.7/571.8 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  571.7/571.8 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  571.7/571.8 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  571.7/571.8 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  571.7/571.8 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  571.7/571.8 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  571.7/571.8 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  571.7/571.8 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  571.7/571.8 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  571.7/571.8 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  571.7/571.8 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  571.7/571.8 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  571.7/571.8 MB 17.8 MB/s eta 0:00:01
     ---------------------------------------- 571.8/571.8 MB 15.1 MB/s  0:00:35
✔ Download and installation successful
You can now load the package via spacy.load('fr_core_news_lg')

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: C:\Users\balda\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Collecting nl-core-news-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/nl_core_news_lg-3.8.0/nl_core_news_lg-3.8.0-py3-none-any.whl (568.1 MB)
     ---------------------------------------- 0.0/568.1 MB ? eta -:--:--
     ---------------------------------------- 0.0/568.1 MB ? eta -:--:--
     ---------------------------------------- 0.0/568.1 MB ? eta -:--:--
     --------------------------------------- 3.4/568.1 MB 16.8 MB/s eta 0:00:34
     --------------------------------------- 5.5/568.1 MB 17.7 MB/s eta 0:00:32
      ------------------------------------- 11.3/568.1 MB 18.1 MB/s eta 0:00:31
      ------------------------------------- 14.2/568.1 MB 16.8 MB/s eta 0:00:34
     - ------------------------------------ 18.9/568.1 MB 18.1 MB/s eta 0:00:31
     - ------------------------------------ 21.8/568.1 MB 17.4 MB/s eta 0:00:32
     - ------------------------------------ 24.9/568.1 MB 17.0 MB/s eta 0:00:33
     - ------------------------------------ 28.0/568.1 MB 16.8 MB/s eta 0:00:33
     -- ----------------------------------- 31.2/568.1 MB 16.8 MB/s eta 0:00:32
     -- ----------------------------------- 34.3/568.1 MB 16.4 MB/s eta 0:00:33
     -- ----------------------------------- 37.7/568.1 MB 16.4 MB/s eta 0:00:33
     -- ----------------------------------- 41.2/568.1 MB 16.4 MB/s eta 0:00:33
     -- ----------------------------------- 44.6/568.1 MB 16.5 MB/s eta 0:00:32
     --- ---------------------------------- 48.5/568.1 MB 16.5 MB/s eta 0:00:32
     --- ---------------------------------- 51.9/568.1 MB 16.5 MB/s eta 0:00:32
     --- ---------------------------------- 55.6/568.1 MB 16.6 MB/s eta 0:00:31
     --- ---------------------------------- 59.2/568.1 MB 16.7 MB/s eta 0:00:31
     ---- --------------------------------- 62.1/568.1 MB 16.5 MB/s eta 0:00:31
     ---- --------------------------------- 65.8/568.1 MB 16.5 MB/s eta 0:00:31
     ---- --------------------------------- 69.5/568.1 MB 16.6 MB/s eta 0:00:31
     ---- --------------------------------- 73.4/568.1 MB 16.7 MB/s eta 0:00:30
     ----- -------------------------------- 77.1/568.1 MB 16.7 MB/s eta 0:00:30
     ----- -------------------------------- 80.5/568.1 MB 16.7 MB/s eta 0:00:30
     ----- -------------------------------- 84.1/568.1 MB 16.7 MB/s eta 0:00:30
     ----- -------------------------------- 87.8/568.1 MB 16.7 MB/s eta 0:00:29
     ------ ------------------------------- 91.5/568.1 MB 16.7 MB/s eta 0:00:29
     ------ ------------------------------- 94.9/568.1 MB 16.7 MB/s eta 0:00:29
     ------ ------------------------------- 98.6/568.1 MB 16.8 MB/s eta 0:00:28
     ------ ------------------------------ 102.0/568.1 MB 16.8 MB/s eta 0:00:28
     ------ ------------------------------ 105.9/568.1 MB 16.8 MB/s eta 0:00:28
     ------- ----------------------------- 109.6/568.1 MB 16.9 MB/s eta 0:00:28
     ------- ----------------------------- 113.5/568.1 MB 16.9 MB/s eta 0:00:27
     ------- ----------------------------- 117.2/568.1 MB 16.9 MB/s eta 0:00:27
     ------- ----------------------------- 121.1/568.1 MB 17.0 MB/s eta 0:00:27
     -------- ---------------------------- 125.0/568.1 MB 17.0 MB/s eta 0:00:27
     -------- ---------------------------- 128.7/568.1 MB 17.0 MB/s eta 0:00:26
     -------- ---------------------------- 132.6/568.1 MB 17.0 MB/s eta 0:00:26
     -------- ---------------------------- 136.3/568.1 MB 17.1 MB/s eta 0:00:26
     --------- --------------------------- 140.0/568.1 MB 17.1 MB/s eta 0:00:26
     --------- --------------------------- 143.1/568.1 MB 17.0 MB/s eta 0:00:25
     --------- --------------------------- 146.8/568.1 MB 17.1 MB/s eta 0:00:25
     --------- --------------------------- 150.7/568.1 MB 17.1 MB/s eta 0:00:25
     ---------- -------------------------- 154.4/568.1 MB 17.1 MB/s eta 0:00:25
     ---------- -------------------------- 157.8/568.1 MB 17.1 MB/s eta 0:00:25
     ---------- -------------------------- 161.5/568.1 MB 17.1 MB/s eta 0:00:24
     ---------- -------------------------- 164.9/568.1 MB 17.0 MB/s eta 0:00:24
     ---------- -------------------------- 168.6/568.1 MB 17.1 MB/s eta 0:00:24
     ----------- ------------------------- 172.5/568.1 MB 17.1 MB/s eta 0:00:24
     ----------- ------------------------- 175.9/568.1 MB 17.1 MB/s eta 0:00:23
     ----------- ------------------------- 179.8/568.1 MB 17.1 MB/s eta 0:00:23
     ----------- ------------------------- 183.5/568.1 MB 17.1 MB/s eta 0:00:23
     ------------ ------------------------ 187.2/568.1 MB 17.1 MB/s eta 0:00:23
     ------------ ------------------------ 190.8/568.1 MB 17.1 MB/s eta 0:00:23
     ------------ ------------------------ 194.5/568.1 MB 17.1 MB/s eta 0:00:22
     ------------ ------------------------ 198.4/568.1 MB 17.1 MB/s eta 0:00:22
     ------------- ----------------------- 202.1/568.1 MB 17.1 MB/s eta 0:00:22
     ------------- ----------------------- 205.8/568.1 MB 17.1 MB/s eta 0:00:22
     ------------- ----------------------- 209.5/568.1 MB 17.1 MB/s eta 0:00:21
     ------------- ----------------------- 212.9/568.1 MB 17.1 MB/s eta 0:00:21
     -------------- ---------------------- 215.7/568.1 MB 17.1 MB/s eta 0:00:21
     -------------- ---------------------- 219.4/568.1 MB 17.1 MB/s eta 0:00:21
     -------------- ---------------------- 223.3/568.1 MB 17.1 MB/s eta 0:00:21
     -------------- ---------------------- 227.0/568.1 MB 17.1 MB/s eta 0:00:20
     --------------- --------------------- 230.9/568.1 MB 17.1 MB/s eta 0:00:20
     --------------- --------------------- 234.6/568.1 MB 17.1 MB/s eta 0:00:20
     --------------- --------------------- 238.3/568.1 MB 17.1 MB/s eta 0:00:20
     --------------- --------------------- 242.2/568.1 MB 17.1 MB/s eta 0:00:20
     ---------------- -------------------- 245.9/568.1 MB 17.2 MB/s eta 0:00:19
     ---------------- -------------------- 249.0/568.1 MB 17.1 MB/s eta 0:00:19
     ---------------- -------------------- 253.0/568.1 MB 17.2 MB/s eta 0:00:19
     ---------------- -------------------- 256.6/568.1 MB 17.2 MB/s eta 0:00:19
     ---------------- -------------------- 260.6/568.1 MB 17.2 MB/s eta 0:00:18
     ----------------- ------------------- 264.2/568.1 MB 17.2 MB/s eta 0:00:18
     ----------------- ------------------- 268.2/568.1 MB 17.3 MB/s eta 0:00:18
     ----------------- ------------------- 271.8/568.1 MB 17.2 MB/s eta 0:00:18
     ----------------- ------------------- 275.5/568.1 MB 17.2 MB/s eta 0:00:17
     ------------------ ------------------ 279.2/568.1 MB 17.2 MB/s eta 0:00:17
     ------------------ ------------------ 282.9/568.1 MB 17.2 MB/s eta 0:00:17
     ------------------ ------------------ 286.5/568.1 MB 17.3 MB/s eta 0:00:17
     ------------------ ------------------ 290.2/568.1 MB 17.3 MB/s eta 0:00:17
     ------------------- ----------------- 294.1/568.1 MB 17.3 MB/s eta 0:00:16
     ------------------- ----------------- 297.8/568.1 MB 17.4 MB/s eta 0:00:16
     ------------------- ----------------- 301.7/568.1 MB 17.4 MB/s eta 0:00:16
     ------------------- ----------------- 305.4/568.1 MB 17.4 MB/s eta 0:00:16
     -------------------- ---------------- 309.1/568.1 MB 17.4 MB/s eta 0:00:15
     -------------------- ---------------- 312.5/568.1 MB 17.4 MB/s eta 0:00:15
     -------------------- ---------------- 316.1/568.1 MB 17.4 MB/s eta 0:00:15
     -------------------- ---------------- 320.1/568.1 MB 17.4 MB/s eta 0:00:15
     --------------------- --------------- 323.7/568.1 MB 17.5 MB/s eta 0:00:14
     --------------------- --------------- 327.4/568.1 MB 17.5 MB/s eta 0:00:14
     --------------------- --------------- 331.1/568.1 MB 17.5 MB/s eta 0:00:14
     --------------------- --------------- 334.8/568.1 MB 17.5 MB/s eta 0:00:14
     ---------------------- -------------- 338.7/568.1 MB 17.5 MB/s eta 0:00:14
     ---------------------- -------------- 342.4/568.1 MB 17.5 MB/s eta 0:00:13
     ---------------------- -------------- 346.3/568.1 MB 17.5 MB/s eta 0:00:13
     ---------------------- -------------- 350.0/568.1 MB 17.6 MB/s eta 0:00:13
     ----------------------- ------------- 353.6/568.1 MB 17.6 MB/s eta 0:00:13
     ----------------------- ------------- 357.0/568.1 MB 17.6 MB/s eta 0:00:13
     ----------------------- ------------- 361.0/568.1 MB 17.6 MB/s eta 0:00:12
     ----------------------- ------------- 364.9/568.1 MB 17.6 MB/s eta 0:00:12
     ------------------------ ------------ 368.6/568.1 MB 17.6 MB/s eta 0:00:12
     ------------------------ ------------ 372.5/568.1 MB 17.6 MB/s eta 0:00:12
     ------------------------ ------------ 376.4/568.1 MB 17.6 MB/s eta 0:00:11
     ------------------------ ------------ 380.1/568.1 MB 17.6 MB/s eta 0:00:11
     ------------------------- ----------- 384.0/568.1 MB 17.6 MB/s eta 0:00:11
     ------------------------- ----------- 388.0/568.1 MB 17.6 MB/s eta 0:00:11
     ------------------------- ----------- 391.9/568.1 MB 17.6 MB/s eta 0:00:11
     ------------------------- ----------- 395.6/568.1 MB 17.6 MB/s eta 0:00:10
     -------------------------- ---------- 399.5/568.1 MB 17.6 MB/s eta 0:00:10
     -------------------------- ---------- 403.2/568.1 MB 17.6 MB/s eta 0:00:10
     -------------------------- ---------- 406.8/568.1 MB 17.6 MB/s eta 0:00:10
     -------------------------- ---------- 410.8/568.1 MB 17.6 MB/s eta 0:00:09
     -------------------------- ---------- 414.4/568.1 MB 17.6 MB/s eta 0:00:09
     --------------------------- --------- 418.1/568.1 MB 17.6 MB/s eta 0:00:09
     --------------------------- --------- 421.8/568.1 MB 17.7 MB/s eta 0:00:09
     --------------------------- --------- 425.7/568.1 MB 17.7 MB/s eta 0:00:09
     --------------------------- --------- 429.1/568.1 MB 17.7 MB/s eta 0:00:08
     ---------------------------- -------- 433.1/568.1 MB 17.7 MB/s eta 0:00:08
     ---------------------------- -------- 436.7/568.1 MB 17.7 MB/s eta 0:00:08
     ---------------------------- -------- 440.4/568.1 MB 17.7 MB/s eta 0:00:08
     ---------------------------- -------- 444.1/568.1 MB 17.7 MB/s eta 0:00:07
     ----------------------------- ------- 448.0/568.1 MB 17.7 MB/s eta 0:00:07
     ----------------------------- ------- 451.7/568.1 MB 17.7 MB/s eta 0:00:07
     ----------------------------- ------- 455.6/568.1 MB 17.7 MB/s eta 0:00:07
     ----------------------------- ------- 459.3/568.1 MB 17.7 MB/s eta 0:00:07
     ------------------------------ ------ 462.9/568.1 MB 17.7 MB/s eta 0:00:06
     ------------------------------ ------ 466.9/568.1 MB 17.8 MB/s eta 0:00:06
     ------------------------------ ------ 470.5/568.1 MB 17.8 MB/s eta 0:00:06
     ------------------------------ ------ 474.5/568.1 MB 17.8 MB/s eta 0:00:06
     ------------------------------- ----- 477.9/568.1 MB 17.8 MB/s eta 0:00:06
     ------------------------------- ----- 481.8/568.1 MB 17.8 MB/s eta 0:00:05
     ------------------------------- ----- 485.2/568.1 MB 17.8 MB/s eta 0:00:05
     ------------------------------- ----- 488.9/568.1 MB 17.8 MB/s eta 0:00:05
     -------------------------------- ---- 492.8/568.1 MB 17.8 MB/s eta 0:00:05
     -------------------------------- ---- 496.5/568.1 MB 17.8 MB/s eta 0:00:05
     -------------------------------- ---- 500.4/568.1 MB 17.8 MB/s eta 0:00:04
     -------------------------------- ---- 504.1/568.1 MB 17.8 MB/s eta 0:00:04
     --------------------------------- --- 508.0/568.1 MB 17.9 MB/s eta 0:00:04
     --------------------------------- --- 511.7/568.1 MB 17.9 MB/s eta 0:00:04
     --------------------------------- --- 515.4/568.1 MB 17.9 MB/s eta 0:00:03
     --------------------------------- --- 518.8/568.1 MB 17.8 MB/s eta 0:00:03
     ---------------------------------- -- 522.7/568.1 MB 17.8 MB/s eta 0:00:03
     ---------------------------------- -- 526.6/568.1 MB 17.8 MB/s eta 0:00:03
     ---------------------------------- -- 530.3/568.1 MB 17.8 MB/s eta 0:00:03
     ---------------------------------- -- 534.2/568.1 MB 17.8 MB/s eta 0:00:02
     ----------------------------------- - 538.2/568.1 MB 17.8 MB/s eta 0:00:02
     ----------------------------------- - 541.9/568.1 MB 17.9 MB/s eta 0:00:02
     ----------------------------------- - 545.5/568.1 MB 17.8 MB/s eta 0:00:02
     ----------------------------------- - 549.2/568.1 MB 17.8 MB/s eta 0:00:02
     ------------------------------------  553.1/568.1 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  556.8/568.1 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  560.7/568.1 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  564.4/568.1 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  567.8/568.1 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  567.8/568.1 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  567.8/568.1 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  567.8/568.1 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  567.8/568.1 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  567.8/568.1 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  567.8/568.1 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  567.8/568.1 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  567.8/568.1 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  567.8/568.1 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  567.8/568.1 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  567.8/568.1 MB 17.8 MB/s eta 0:00:01
     ------------------------------------  567.8/568.1 MB 17.8 MB/s eta 0:00:01
     ---------------------------------------- 568.1/568.1 MB 15.2 MB/s  0:00:35
✔ Download and installation successful
You can now load the package via spacy.load('nl_core_news_lg')

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: C:\Users\balda\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [4]:
nlp_en = spacy.load("en_core_web_lg")
nlp_fr = spacy.load("fr_core_news_lg")
nlp_nl = spacy.load("nl_core_news_lg")

In [5]:
base_path = Path("corpus_original")

corpus_paths = {
    "HaveYourSay_EN": base_path / "HaveYourSay" / "EN",
    "HaveYourSay_FR": base_path / "HaveYourSay" / "FR",
    "HaveYourSay_NL": base_path / "HaveYourSay" / "NL",
    "Jurisprudence_FR": base_path / "Jurisprudence" / "FR",
    "Jurisprudence_NL": base_path / "Jurisprudence" / "NL",
}

In [6]:
documents = []

for corpus, folder in corpus_paths.items():
    for file_path in folder.glob("*.txt"):
        documents.append({
            "corpus": corpus,
            "fichier": file_path.name,
            "texte": file_path.read_text(encoding="utf-8")
        })

df = pd.DataFrame(documents)

df

,corpus,fichier,texte
0,HaveYourSay_EN,HYS_EN_01.txt,Ciaran Kenneally \nIreland\nAs a longstanding ...
1,HaveYourSay_EN,HYS_EN_02.txt,"Etienne MARICQ \nBelgium\nAs a radio-amateur, ..."
2,HaveYourSay_EN,HYS_EN_03.txt,Martin Janse van Rensburg \nSouth Africa\nI st...
3,HaveYourSay_EN,HYS_EN_04.txt,Susan Murphy \nIreland\nI am an Irish/British ...
4,HaveYourSay_EN,HYS_EN_05.txt,Sara Pellegrino \nItaly\nThis is a serious lac...
5,HaveYourSay_EN,HYS_EN_06.txt,Vytautas Butrimas \nLithuania\nIn looking at t...
6,HaveYourSay_EN,HYS_EN_07.txt,Nicolas Overloop \nBelgium\nNot the right plac...
7,HaveYourSay_EN,HYS_EN_08.txt,Matt Barringer \nUnited Kingdom\nThe right of ...
8,HaveYourSay_EN,HYS_EN_09.txt,Alberto COTTICA \nItaly\nI am someone who own ...
9,HaveYourSay_EN,HYS_EN_10.txt,Titia Deurvorst \nNetherlands \nAnimals have i...
10,HaveYourSay_FR,HYS_FR_01.txt,Joly Sylvaine\nFrance\nQuoi qu il en soit il f...
11,HaveYourSay_FR,HYS_FR_02.txt,Hubert de Bon \nFrance\nMon avis concerne le p...
12,HaveYourSay_FR,HYS_FR_03.txt,Bonnard Monique \nFrance\nLes semences doivent...
13,HaveYourSay_FR,HYS_FR_04.txt,Gilbert RIBES\nFrance\nVous pourrez trouver ci...
14,HaveYourSay_FR,HYS_FR_05.txt,Véronique Deschamps \nFrance\nJe vis dans une ...
15,HaveYourSay_FR,HYS_FR_06.txt,"Stephane Cardinali \nFrance\nBonjour, Étant in..."
16,HaveYourSay_FR,HYS_FR_07.txt,Patrick Moriceau \nFrance\nIl faut AU MINIMUM ...
17,HaveYourSay_FR,HYS_FR_08.txt,David Sokol \nBelgique\nIl me semblerait essen...
18,HaveYourSay_FR,HYS_FR_09.txt,"Marie-Paule Fratani \nFrance\nBonjour, L'alime..."
19,HaveYourSay_FR,HYS_FR_10.txt,"Jean-Marc Léculier \nFrance\nBonjour, je const..."
20,HaveYourSay_NL,HYS_NL_01.txt,Krien Hansen \nBelgië\nDe wetgeving voor de pr...
21,HaveYourSay_NL,HYS_NL_02.txt,Geert Bollé \nBelgië\nBemerkingen bg consultin...
22,HaveYourSay_NL,HYS_NL_03.txt,Leonardo Daemen \nSpanje\nMet betrekking tot d...
23,HaveYourSay_NL,HYS_NL_04.txt,Caroline j Den Hertog \nNederland\nIk ben over...
24,HaveYourSay_NL,HYS_NL_05.txt,Said Jamil \nNederland\nIk ben sterk tegеn elk...
25,Jurisprudence_FR,JUR_FR_01.txt,Numéro du rôle : 5118 \nArrêt n° 5/2012 \ndu 1...
26,Jurisprudence_FR,JUR_FR_02.txt,"CONSEIL D'ETAT, SECTION DU CONTENTIEUX ADMINIS..."
27,Jurisprudence_FR,JUR_FR_03.txt,"CONSEIL D'ETAT, SECTION DU CONTENTIEUX ADMINIS..."
28,Jurisprudence_FR,JUR_FR_04.txt,"CONSEIL D'ÉTAT, SECTION DU CONTENTIEUX ADMINIS..."
29,Jurisprudence_FR,JUR_FR_05.txt,"CONSEIL D'ÉTAT, SECTION DU CONTENTIEUX ADMINIS..."
30,Jurisprudence_NL,JUR_NL_01.txt,"RAAD VAN STATE, AFDELING BESTUURSRECHTSPRAAK \..."
31,Jurisprudence_NL,JUR_NL_02.txt,"RAAD VAN STATE, AFDELING BESTUURSRECHTSPRAAK \..."
32,Jurisprudence_NL,JUR_NL_03.txt,"RAAD VAN STATE, AFDELING BESTUURSRECHTSPRAAK \..."
33,Jurisprudence_NL,JUR_NL_04.txt,"RAAD VAN STATE, AFDELING BESTUURSRECHTSPRAAK \..."
34,Jurisprudence_NL,JUR_NL_05.txt,"RAAD VAN STATE, AFDELING BESTUURSRECHTSPRAAK \..."

In [7]:
def clean_text(text):
    text = text.replace("\n", " ")
    text = text.replace("\t", " ")
    text = " ".join(text.split())
    return text


def get_nlp_model(corpus):
    if corpus.endswith("_EN"):
        return nlp_en
    elif corpus.endswith("_FR"):
        return nlp_fr
    elif corpus.endswith("_NL"):
        return nlp_nl

In [8]:
labels_utiles = ["PERSON", "PER", "ORG", "GPE", "LOC"]

resultats = []

for _, row in df.iterrows():
    nlp = get_nlp_model(row["corpus"])
    texte_nettoye = clean_text(row["texte"])
    doc = nlp(texte_nettoye)

    for ent in doc.ents:
        label = ent.label_

        if label in labels_utiles:
            if label == "PER":
                label = "PERSON"
            elif label == "GPE":
                label = "LOC"

            resultats.append({
                "corpus": row["corpus"],
                "fichier": row["fichier"],
                "entite": ent.text,
                "label": label
            })

ner_df = pd.DataFrame(resultats)

ner_df = ner_df.drop_duplicates().reset_index(drop=True)

ner_df

,corpus,fichier,entite,label
0,HaveYourSay_EN,HYS_EN_01.txt,Ciaran Kenneally,PERSON
1,HaveYourSay_EN,HYS_EN_01.txt,Ireland,LOC
2,HaveYourSay_EN,HYS_EN_01.txt,Dáil Éireann,PERSON
3,HaveYourSay_EN,HYS_EN_01.txt,State,ORG
4,HaveYourSay_EN,HYS_EN_01.txt,Ken OFlynn,PERSON
...,...,...,...,...
685,Jurisprudence_NL,JUR_NL_05.txt,Raad voor Vergunningsbetwistingen de,ORG
686,Jurisprudence_NL,JUR_NL_05.txt,Brussel,LOC
687,Jurisprudence_NL,JUR_NL_05.txt,Carlo Adams,PERSON
688,Jurisprudence_NL,JUR_NL_05.txt,Frédéric Vanneste,PERSON
689,Jurisprudence_NL,JUR_NL_05.txt,Elisabeth Impens,PERSON

In [9]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

display(ner_df)

,corpus,fichier,entite,label
0,HaveYourSay_EN,HYS_EN_01.txt,Ciaran Kenneally,PERSON
1,HaveYourSay_EN,HYS_EN_01.txt,Ireland,LOC
2,HaveYourSay_EN,HYS_EN_01.txt,Dáil Éireann,PERSON
3,HaveYourSay_EN,HYS_EN_01.txt,State,ORG
4,HaveYourSay_EN,HYS_EN_01.txt,Ken OFlynn,PERSON
5,HaveYourSay_EN,HYS_EN_01.txt,TD,ORG
6,HaveYourSay_EN,HYS_EN_01.txt,Ken O Flynn,PERSON
7,HaveYourSay_EN,HYS_EN_02.txt,Etienne MARICQ,PERSON
8,HaveYourSay_EN,HYS_EN_02.txt,Belgium,LOC
9,HaveYourSay_EN,HYS_EN_02.txt,Spain,LOC
10,HaveYourSay_EN,HYS_EN_02.txt,France,LOC
11,HaveYourSay_EN,HYS_EN_02.txt,FNRASEC/Adrasec,ORG
12,HaveYourSay_EN,HYS_EN_02.txt,URE EMCOM,ORG
13,HaveYourSay_EN,HYS_EN_02.txt,Red Cross ERIECOM,ORG
14,HaveYourSay_EN,HYS_EN_02.txt,Portugal,LOC
15,HaveYourSay_EN,HYS_EN_02.txt,VHF,ORG
16,HaveYourSay_EN,HYS_EN_02.txt,UHF,ORG
17,HaveYourSay_EN,HYS_EN_02.txt,HF,ORG
18,HaveYourSay_EN,HYS_EN_02.txt,TETRAPOL,ORG
19,HaveYourSay_EN,HYS_EN_02.txt,Europe,LOC
20,HaveYourSay_EN,HYS_EN_02.txt,RadioAmateur,ORG
21,HaveYourSay_EN,HYS_EN_02.txt,ARES - Amateur Radio Emergency Services,ORG
22,HaveYourSay_EN,HYS_EN_03.txt,Martin Janse van Rensburg,PERSON
23,HaveYourSay_EN,HYS_EN_03.txt,ESSPASS,ORG
24,HaveYourSay_EN,HYS_EN_04.txt,Susan Murphy,PERSON
25,HaveYourSay_EN,HYS_EN_04.txt,Switzerland,LOC
26,HaveYourSay_EN,HYS_EN_04.txt,the International School of Geneva,ORG
27,HaveYourSay_EN,HYS_EN_04.txt,the Board/Staff Association,ORG
28,HaveYourSay_EN,HYS_EN_04.txt,UK,LOC
29,HaveYourSay_EN,HYS_EN_04.txt,Ireland,LOC
30,HaveYourSay_EN,HYS_EN_04.txt,the Ecolint Board,ORG
31,HaveYourSay_EN,HYS_EN_04.txt,Geneva,LOC
32,HaveYourSay_EN,HYS_EN_04.txt,The Board,ORG
33,HaveYourSay_EN,HYS_EN_04.txt,Virgin CFO,ORG
34,HaveYourSay_EN,HYS_EN_04.txt,UN,ORG
35,HaveYourSay_EN,HYS_EN_04.txt,Irelands DFA,ORG
36,HaveYourSay_EN,HYS_EN_04.txt,DFA,ORG
37,HaveYourSay_EN,HYS_EN_04.txt,An Garda Síochána,PERSON
38,HaveYourSay_EN,HYS_EN_04.txt,Art,ORG
39,HaveYourSay_EN,HYS_EN_04.txt,GDPR,ORG
40,HaveYourSay_EN,HYS_EN_04.txt,CJ,PERSON
41,HaveYourSay_EN,HYS_EN_04.txt,EU,ORG
42,HaveYourSay_EN,HYS_EN_04.txt,Irish Ombudsman,ORG
43,HaveYourSay_EN,HYS_EN_04.txt,Protected Disclosures,ORG
44,HaveYourSay_EN,HYS_EN_04.txt,DFA/Garda/IPS,ORG
45,HaveYourSay_EN,HYS_EN_04.txt,Garda,ORG
46,HaveYourSay_EN,HYS_EN_04.txt,IPS,ORG
47,HaveYourSay_EN,HYS_EN_04.txt,GSOC,ORG
48,HaveYourSay_EN,HYS_EN_04.txt,Fiosrú,PERSON
49,HaveYourSay_EN,HYS_EN_04.txt,Garda,PERSON
50,HaveYourSay_EN,HYS_EN_04.txt,Simon Coveney,PERSON
51,HaveYourSay_EN,HYS_EN_04.txt,Brendan Howlin TD,PERSON
52,HaveYourSay_EN,HYS_EN_04.txt,Micheál Martin,PERSON
53,HaveYourSay_EN,HYS_EN_04.txt,Luke Ming Flanagan MEP,PERSON
54,HaveYourSay_EN,HYS_EN_04.txt,Michael McGrath,PERSON
55,HaveYourSay_EN,HYS_EN_04.txt,Simon Harris,PERSON
56,HaveYourSay_EN,HYS_EN_04.txt,Irelands EU,PERSON
57,HaveYourSay_EN,HYS_EN_04.txt,Jonathan Claridge,PERSON
58,HaveYourSay_EN,HYS_EN_04.txt,Timeline,ORG
59,HaveYourSay_EN,HYS_EN_04.txt,PAC,ORG
60,HaveYourSay_EN,HYS_EN_04.txt,Irelands,LOC
61,HaveYourSay_EN,HYS_EN_04.txt,Arts 913,ORG
62,HaveYourSay_EN,HYS_EN_04.txt,Oireachtas,ORG
63,HaveYourSay_EN,HYS_EN_04.txt,Foreign Affairs/Justice,ORG
64,HaveYourSay_EN,HYS_EN_04.txt,DPC,ORG
65,HaveYourSay_EN,HYS_EN_04.txt,the EC Representation,ORG
66,HaveYourSay_EN,HYS_EN_05.txt,Sara Pellegrino,PERSON
67,HaveYourSay_EN,HYS_EN_05.txt,Italy,LOC
68,HaveYourSay_EN,HYS_EN_05.txt,EU,ORG
69,HaveYourSay_EN,HYS_EN_06.txt,Vytautas Butrimas,PERSON
70,HaveYourSay_EN,HYS_EN_06.txt,Lithuania,LOC
71,HaveYourSay_EN,HYS_EN_06.txt,CRA,ORG
72,HaveYourSay_EN,HYS_EN_07.txt,Nicolas Overloop,PERSON
73,HaveYourSay_EN,HYS_EN_07.txt,Italy,LOC
74,HaveYourSay_EN,HYS_EN_07.txt,TFR,ORG
75,HaveYourSay_EN,HYS_EN_08.txt,Matt Barringer,PERSON
76,HaveYourSay_EN,HYS_EN_08.txt,United Kingdom,LOC
77,HaveYourSay_EN,HYS_EN_09.txt,Alberto COTTICA,PERSON
78,HaveYourSay_EN,HYS_EN_09.txt,Italy,LOC
79,HaveYourSay_EN,HYS_EN_10.txt,Titia Deurvorst Netherlands Animals,ORG
80,HaveYourSay_EN,HYS_EN_10.txt,EU,ORG
81,HaveYourSay_FR,HYS_FR_01.txt,Joly Sylvaine France,PERSON
82,HaveYourSay_FR,HYS_FR_02.txt,Hubert de Bon France,PERSON
83,HaveYourSay_FR,HYS_FR_03.txt,Bonnard Monique France,PERSON
84,HaveYourSay_FR,HYS_FR_04.txt,Gilbert RIBES,PERSON
85,HaveYourSay_FR,HYS_FR_04.txt,France,LOC
86,HaveYourSay_FR,HYS_FR_04.txt,lEcole Polytechnique,ORG
87,HaveYourSay_FR,HYS_FR_04.txt,Madame Christine Lagarde,PERSON
88,HaveYourSay_FR,HYS_FR_04.txt,Présidente de la BCE,ORG
89,HaveYourSay_FR,HYS_FR_04.txt,BEI,ORG
90,HaveYourSay_FR,HYS_FR_04.txt,BCE,ORG
91,HaveYourSay_FR,HYS_FR_04.txt,Christine Lagarde,PERSON
92,HaveYourSay_FR,HYS_FR_04.txt,Madame Von der Leyen,PERSON
93,HaveYourSay_FR,HYS_FR_05.txt,Véronique Deschamps France,PERSON
94,HaveYourSay_FR,HYS_FR_05.txt,cathédrale de Saint malo intra-muros,LOC
95,HaveYourSay_FR,HYS_FR_05.txt,AIRBNB,ORG
96,HaveYourSay_FR,HYS_FR_05.txt,Maître Moncoq,PERSON
97,HaveYourSay_FR,HYS_FR_05.txt,Saint-Malo,LOC
98,HaveYourSay_FR,HYS_FR_05.txt,cour d'appel de,LOC
99,HaveYourSay_FR,HYS_FR_05.txt,Rennes,LOC
100,HaveYourSay_FR,HYS_FR_05.txt,Dan Jøgersen,PERSON
101,HaveYourSay_FR,HYS_FR_05.txt,Malouine,LOC
102,HaveYourSay_FR,HYS_FR_05.txt,Conseil,ORG
103,HaveYourSay_FR,HYS_FR_05.txt,AG,ORG
104,HaveYourSay_FR,HYS_FR_05.txt,Européen,LOC
105,HaveYourSay_FR,HYS_FR_05.txt,Bretagne,LOC
106,HaveYourSay_FR,HYS_FR_05.txt,Marco Gasparinetti,PERSON
107,HaveYourSay_FR,HYS_FR_05.txt,Venise,LOC
108,HaveYourSay_FR,HYS_FR_05.txt,SAINT-MALO,LOC
109,HaveYourSay_FR,HYS_FR_05.txt,Chypre,LOC
110,HaveYourSay_FR,HYS_FR_05.txt,Corfou,LOC
111,HaveYourSay_FR,HYS_FR_05.txt,Crète,LOC
112,HaveYourSay_FR,HYS_FR_05.txt,Dubrovnik,LOC
113,HaveYourSay_FR,HYS_FR_05.txt,BIENVENUS,LOC
114,HaveYourSay_FR,HYS_FR_06.txt,Stephane Cardinali France Bonjour,PERSON
115,HaveYourSay_FR,HYS_FR_06.txt,Corse,LOC
116,HaveYourSay_FR,HYS_FR_06.txt,Amazonienne,LOC
117,HaveYourSay_FR,HYS_FR_06.txt,Équatoriale Africaine,LOC
118,HaveYourSay_FR,HYS_FR_06.txt,One Health,ORG
119,HaveYourSay_FR,HYS_FR_06.txt,la Corse,LOC
120,HaveYourSay_FR,HYS_FR_06.txt,Bastia,LOC
121,HaveYourSay_FR,HYS_FR_06.txt,Ajaccio,LOC
122,HaveYourSay_FR,HYS_FR_06.txt,île d'Elbe,LOC
123,HaveYourSay_FR,HYS_FR_06.txt,Piombino,LOC
124,HaveYourSay_FR,HYS_FR_06.txt,Bonifacio,LOC
125,HaveYourSay_FR,HYS_FR_06.txt,Sardaigne,LOC
126,HaveYourSay_FR,HYS_FR_06.txt,Stéphane Cardinali Président,PERSON
127,HaveYourSay_FR,HYS_FR_06.txt,Union Régionale,ORG
128,HaveYourSay_FR,HYS_FR_06.txt,Energia Nostra,ORG
129,HaveYourSay_FR,HYS_FR_06.txt,Energie et environnement,ORG
130,HaveYourSay_FR,HYS_FR_06.txt,Défenseur,LOC
131,HaveYourSay_FR,HYS_FR_07.txt,Patrick Moriceau France,PERSON
132,HaveYourSay_FR,HYS_FR_08.txt,David Sokol Belgique,PERSON
133,HaveYourSay_FR,HYS_FR_08.txt,A,LOC
134,HaveYourSay_FR,HYS_FR_08.txt,B,LOC
135,HaveYourSay_FR,HYS_FR_08.txt,C,LOC
136,HaveYourSay_FR,HYS_FR_08.txt,Idée,PERSON
137,HaveYourSay_FR,HYS_FR_09.txt,Marie-Paule Fratani France Bonjour,PERSON
138,HaveYourSay_FR,HYS_FR_09.txt,Commission européenne,ORG
139,HaveYourSay_FR,HYS_FR_09.txt,BAH,LOC
140,HaveYourSay_FR,HYS_FR_09.txt,Pet Food,ORG
141,HaveYourSay_FR,HYS_FR_10.txt,Jean-Marc Léculier France,PERSON
142,HaveYourSay_FR,HYS_FR_10.txt,europe,LOC
143,HaveYourSay_NL,HYS_NL_01.txt,Krien Hansen,PERSON
144,HaveYourSay_NL,HYS_NL_01.txt,België,LOC
145,HaveYourSay_NL,HYS_NL_02.txt,Geert Bollé,PERSON
146,HaveYourSay_NL,HYS_NL_02.txt,nv,ORG
147,HaveYourSay_NL,HYS_NL_02.txt,Stadsradio Vlaanderen,ORG
148,HaveYourSay_NL,HYS_NL_02.txt,Vlaamse Regering,ORG
149,HaveYourSay_NL,HYS_NL_02.txt,Raad van State,ORG
150,HaveYourSay_NL,HYS_NL_02.txt,Naamloze vennootschap voor frequentiepakket netwerkradio-omroeporganisatie,ORG
151,HaveYourSay_NL,HYS_NL_02.txt,BG,ORG
152,HaveYourSay_NL,HYS_NL_02.txt,Naamloze vennootschap voor frequentiepakket netwerkradioomroeporganisatie,ORG
153,HaveYourSay_NL,HYS_NL_02.txt,BG Consulting nv,ORG
154,HaveYourSay_NL,HYS_NL_03.txt,Leonardo Daemen,PERSON
155,HaveYourSay_NL,HYS_NL_03.txt,VV,ORG
156,HaveYourSay_NL,HYS_NL_03.txt,STR,ORG
157,HaveYourSay_NL,HYS_NL_03.txt,Rental,ORG
158,HaveYourSay_NL,HYS_NL_03.txt,Spanje,LOC
159,HaveYourSay_NL,HYS_NL_04.txt,Caroline j,PERSON
160,HaveYourSay_NL,HYS_NL_04.txt,Nederland,LOC
161,HaveYourSay_NL,HYS_NL_04.txt,milieubeveiligingsmaatregelen,ORG
162,HaveYourSay_NL,HYS_NL_04.txt,EU,LOC
163,HaveYourSay_NL,HYS_NL_04.txt,natuurafbraak,LOC
164,HaveYourSay_NL,HYS_NL_04.txt,Europa's,LOC
165,HaveYourSay_NL,HYS_NL_05.txt,Said Jamil Nederland,PERSON
166,HaveYourSay_NL,HYS_NL_05.txt,Commissie,ORG
167,HaveYourSay_NL,HYS_NL_05.txt,EU,LOC
168,HaveYourSay_NL,HYS_NL_05.txt,Europa,LOC
169,HaveYourSay_NL,HYS_NL_05.txt,Europese Commissie,ORG
170,Jurisprudence_FR,JUR_FR_01.txt,Octroi,LOC
171,Jurisprudence_FR,JUR_FR_01.txt,Conseil d’Etat,ORG
172,Jurisprudence_FR,JUR_FR_01.txt,Cour constitutionnelle,LOC
173,Jurisprudence_FR,JUR_FR_01.txt,R. Henneuse,PERSON
174,Jurisprudence_FR,JUR_FR_01.txt,M. Bossuyt,PERSON
175,Jurisprudence_FR,JUR_FR_01.txt,E. De Groot,PERSON
176,Jurisprudence_FR,JUR_FR_01.txt,A. Alen,PERSON
177,Jurisprudence_FR,JUR_FR_01.txt,J.-P. Moerman,PERSON
178,Jurisprudence_FR,JUR_FR_01.txt,T. Merckx-Van Goey,PERSON
179,Jurisprudence_FR,JUR_FR_01.txt,F. Daoût,PERSON
180,Jurisprudence_FR,JUR_FR_01.txt,P.-Y. Dutilleux,PERSON
181,Jurisprudence_FR,JUR_FR_01.txt,Roland Rütter,PERSON
182,Jurisprudence_FR,JUR_FR_01.txt,greffe de la Cour,LOC
183,Jurisprudence_FR,JUR_FR_01.txt,Constitution,ORG
184,Jurisprudence_FR,JUR_FR_01.txt,Liers,LOC
185,Jurisprudence_FR,JUR_FR_01.txt,Conseil,ORG
186,Jurisprudence_FR,JUR_FR_01.txt,Me T. Frankin,PERSON
187,Jurisprudence_FR,JUR_FR_01.txt,Bruxelles,LOC
188,Jurisprudence_FR,JUR_FR_01.txt,Me P. Crabbé,PERSON
189,Jurisprudence_FR,JUR_FR_01.txt,Me B. Renson,PERSON
190,Jurisprudence_FR,JUR_FR_01.txt,T. Merckx,PERSON
191,Jurisprudence_FR,JUR_FR_01.txt,Cour constitutionnelle,ORG
192,Jurisprudence_FR,JUR_FR_01.txt,II,PERSON
193,Jurisprudence_FR,JUR_FR_01.txt,Herstal,LOC
194,Jurisprudence_FR,JUR_FR_01.txt,ministre de l’Intérieur,ORG
195,Jurisprudence_FR,JUR_FR_01.txt,Etat,LOC
196,Jurisprudence_FR,JUR_FR_01.txt,Etat belge,ORG
197,Jurisprudence_FR,JUR_FR_01.txt,Constitution de la condition,ORG
198,Jurisprudence_FR,JUR_FR_01.txt,Conseil des ministres,ORG
199,Jurisprudence_FR,JUR_FR_01.txt,A.2,LOC
200,Jurisprudence_FR,JUR_FR_01.txt,A.3,LOC
201,Jurisprudence_FR,JUR_FR_01.txt,A.4,LOC
202,Jurisprudence_FR,JUR_FR_01.txt,Roland Rütter A.6,PERSON
203,Jurisprudence_FR,JUR_FR_01.txt,Cour de cassation,LOC
204,Jurisprudence_FR,JUR_FR_01.txt,- B,PERSON
205,Jurisprudence_FR,JUR_FR_01.txt,Roi,PERSON
206,Jurisprudence_FR,JUR_FR_01.txt,Sûreté de l'Etat ’ de l'administration de la,ORG
207,Jurisprudence_FR,JUR_FR_01.txt,Sûreté publique du service public fédéral,ORG
208,Jurisprudence_FR,JUR_FR_01.txt,Justice,ORG
209,Jurisprudence_FR,JUR_FR_01.txt,ministère de la Défense,ORG
210,Jurisprudence_FR,JUR_FR_01.txt,B.2.1,ORG
211,Jurisprudence_FR,JUR_FR_01.txt,Cour,ORG
212,Jurisprudence_FR,JUR_FR_01.txt,B.2.2,LOC
213,Jurisprudence_FR,JUR_FR_01.txt,B.3,LOC
214,Jurisprudence_FR,JUR_FR_01.txt,Gouvernement,LOC
215,Jurisprudence_FR,JUR_FR_01.txt,Chambre,LOC
216,Jurisprudence_FR,JUR_FR_01.txt,B.4,LOC
217,Jurisprudence_FR,JUR_FR_01.txt,9 B.6,LOC
218,Jurisprudence_FR,JUR_FR_01.txt,B.7,LOC
219,Jurisprudence_FR,JUR_FR_01.txt,B.8,LOC
220,Jurisprudence_FR,JUR_FR_02.txt,CONSEIL,ORG
221,Jurisprudence_FR,JUR_FR_02.txt,SECTION,ORG
222,Jurisprudence_FR,JUR_FR_02.txt,G./A.147.486,PERSON
223,Jurisprudence_FR,JUR_FR_02.txt,VI-16.649,ORG
224,Jurisprudence_FR,JUR_FR_02.txt,WAUTRAETS Yolande,PERSON
225,Jurisprudence_FR,JUR_FR_02.txt,Voie di Messe,LOC
226,Jurisprudence_FR,JUR_FR_02.txt,Tavier,LOC
227,Jurisprudence_FR,JUR_FR_02.txt,Etat,LOC
228,Jurisprudence_FR,JUR_FR_02.txt,Ministre de l’,ORG
229,Jurisprudence_FR,JUR_FR_02.txt,Vice-Première Ministre,ORG
230,Jurisprudence_FR,JUR_FR_02.txt,Ministre des Affaires sociales et de la,ORG
231,Jurisprudence_FR,JUR_FR_02.txt,Yolande WAUTRAETS,PERSON
232,Jurisprudence_FR,JUR_FR_02.txt,Administration,ORG
233,Jurisprudence_FR,JUR_FR_02.txt,Auditeur au Conseil d'Etat,ORG
234,Jurisprudence_FR,JUR_FR_02.txt,LEWALLE,LOC
235,Jurisprudence_FR,JUR_FR_02.txt,Conseiller d'Etat,ORG
236,Jurisprudence_FR,JUR_FR_02.txt,VI-16.649,LOC
237,Jurisprudence_FR,JUR_FR_02.txt,MAHELE,ORG
238,Jurisprudence_FR,JUR_FR_02.txt,Me Jean-Jacques MASQUELIN,PERSON
239,Jurisprudence_FR,JUR_FR_02.txt,Auditeur,ORG
240,Jurisprudence_FR,JUR_FR_02.txt,II,PERSON
241,Jurisprudence_FR,JUR_FR_02.txt,Conseil d'Etat,ORG
242,Jurisprudence_FR,JUR_FR_02.txt,EUR,LOC
243,Jurisprudence_FR,JUR_FR_02.txt,Ministre,ORG
244,Jurisprudence_FR,JUR_FR_02.txt,Monsieur le Ministre,PERSON
245,Jurisprudence_FR,JUR_FR_02.txt,Commission d’aide sociale,ORG
246,Jurisprudence_FR,JUR_FR_02.txt,Conseillère,ORG
247,Jurisprudence_FR,JUR_FR_02.txt,Yves DEPLUS,PERSON
248,Jurisprudence_FR,JUR_FR_02.txt,Considérant,PERSON
249,Jurisprudence_FR,JUR_FR_02.txt,Conseil d’Etat,ORG
250,Jurisprudence_FR,JUR_FR_02.txt,Ministre des Affaires sociales,ORG
251,Jurisprudence_FR,JUR_FR_02.txt,Bruxelles,LOC
252,Jurisprudence_FR,JUR_FR_02.txt,Mme WILLOT-THOMAS,PERSON
253,Jurisprudence_FR,JUR_FR_02.txt,MM. LEWALLE,PERSON
254,Jurisprudence_FR,JUR_FR_02.txt,Mme,PERSON
255,Jurisprudence_FR,JUR_FR_02.txt,Le Greffier,PERSON
256,Jurisprudence_FR,JUR_FR_02.txt,K. LAUVAU,PERSON
257,Jurisprudence_FR,JUR_FR_02.txt,Greffier,LOC
258,Jurisprudence_FR,JUR_FR_02.txt,Président,PERSON
259,Jurisprudence_FR,JUR_FR_02.txt,M.-L. WILLOT-THOMAS,PERSON
260,Jurisprudence_FR,JUR_FR_03.txt,CONSEIL,ORG
261,Jurisprudence_FR,JUR_FR_03.txt,SECTION,ORG
262,Jurisprudence_FR,JUR_FR_03.txt,VI-18.673,PERSON
263,Jurisprudence_FR,JUR_FR_03.txt,RYBICKA Grazyna,ORG
264,Jurisprudence_FR,JUR_FR_03.txt,Stiénon,PERSON
265,Jurisprudence_FR,JUR_FR_03.txt,bte 1,ORG
266,Jurisprudence_FR,JUR_FR_03.txt,Bruxelles,LOC
267,Jurisprudence_FR,JUR_FR_03.txt,Société du Logement de la Région de Bruxelles,ORG
268,Jurisprudence_FR,JUR_FR_03.txt,Me Philippe COENRAETS,PERSON
269,Jurisprudence_FR,JUR_FR_03.txt,Cambre,LOC
270,Jurisprudence_FR,JUR_FR_03.txt,Grazyna,ORG
271,Jurisprudence_FR,JUR_FR_03.txt,Conseil d’Administration de la Société du Logement de la Région de Bruxelles-Capitale,ORG
272,Jurisprudence_FR,JUR_FR_03.txt,M. le Premier,PERSON
273,Jurisprudence_FR,JUR_FR_03.txt,Conseil d'Etat,ORG
274,Jurisprudence_FR,JUR_FR_03.txt,Stéphane SAINT-VITEUX,PERSON
275,Jurisprudence_FR,JUR_FR_03.txt,VI,PERSON
276,Jurisprudence_FR,JUR_FR_03.txt,Grazyna RYBICKA,ORG
277,Jurisprudence_FR,JUR_FR_03.txt,Yves HOUYET,PERSON
278,Jurisprudence_FR,JUR_FR_03.txt,Me Christophe LEPINOIS,PERSON
279,Jurisprudence_FR,JUR_FR_03.txt,II,PERSON
280,Jurisprudence_FR,JUR_FR_03.txt,III,PERSON
281,Jurisprudence_FR,JUR_FR_03.txt,Foyer Jettois,ORG
282,Jurisprudence_FR,JUR_FR_03.txt,Jette,LOC
283,Jurisprudence_FR,JUR_FR_03.txt,Avenue Stiénon,LOC
284,Jurisprudence_FR,JUR_FR_03.txt,Monsieur,PERSON
285,Jurisprudence_FR,JUR_FR_03.txt,Madame Adam,PERSON
286,Jurisprudence_FR,JUR_FR_03.txt,FOYER,ORG
287,Jurisprudence_FR,JUR_FR_03.txt,JETTOIS,ORG
288,Jurisprudence_FR,JUR_FR_03.txt,Société contre remise d’accusé,ORG
289,Jurisprudence_FR,JUR_FR_03.txt,Monsieur A. Callebaut,PERSON
290,Jurisprudence_FR,JUR_FR_03.txt,Madame,PERSON
291,Jurisprudence_FR,JUR_FR_03.txt,SISP,ORG
292,Jurisprudence_FR,JUR_FR_03.txt,sisp,LOC
293,Jurisprudence_FR,JUR_FR_03.txt,Déléguée sociale,ORG
294,Jurisprudence_FR,JUR_FR_03.txt,Bureau Permanent,ORG
295,Jurisprudence_FR,JUR_FR_03.txt,Jules Lahaye,PERSON
296,Jurisprudence_FR,JUR_FR_03.txt,Cette,LOC
297,Jurisprudence_FR,JUR_FR_03.txt,Conseil d'administration,ORG
298,Jurisprudence_FR,JUR_FR_03.txt,Délai imparti,ORG
299,Jurisprudence_FR,JUR_FR_03.txt,société -,ORG
300,Jurisprudence_FR,JUR_FR_03.txt,Recours,PERSON
301,Jurisprudence_FR,JUR_FR_03.txt,Pas de réaction,LOC
302,Jurisprudence_FR,JUR_FR_03.txt,Conseil d'administration de la,ORG
303,Jurisprudence_FR,JUR_FR_03.txt,SOTRA,ORG
304,Jurisprudence_FR,JUR_FR_03.txt,Société du Logement de la Région de Bruxelles-Capitale,ORG
305,Jurisprudence_FR,JUR_FR_03.txt,Considérant,PERSON
306,Jurisprudence_FR,JUR_FR_03.txt,Le Conseil d'administration,ORG
307,Jurisprudence_FR,JUR_FR_03.txt,RECEVABILITE IV,PERSON
308,Jurisprudence_FR,JUR_FR_03.txt,Région de Bruxelles,LOC
309,Jurisprudence_FR,JUR_FR_03.txt,Conseil d’Etat,ORG
310,Jurisprudence_FR,JUR_FR_03.txt,IV,LOC
311,Jurisprudence_FR,JUR_FR_03.txt,confirmative,LOC
312,Jurisprudence_FR,JUR_FR_03.txt,Région de Bruxelles-Capitale,LOC
313,Jurisprudence_FR,JUR_FR_03.txt,Région bruxelloise,LOC
314,Jurisprudence_FR,JUR_FR_03.txt,Mme Odile DAURMONT,PERSON
315,Jurisprudence_FR,JUR_FR_03.txt,Président de chambre,PERSON
316,Jurisprudence_FR,JUR_FR_03.txt,MM. Paul LEWALLE,PERSON
317,Jurisprudence_FR,JUR_FR_03.txt,Conseiller d'Etat,ORG
318,Jurisprudence_FR,JUR_FR_03.txt,Vincent DURIEUX,PERSON
319,Jurisprudence_FR,JUR_FR_03.txt,Greffier,LOC
320,Jurisprudence_FR,JUR_FR_03.txt,Le Président,PERSON
321,Jurisprudence_FR,JUR_FR_03.txt,Odile DAURMONT,PERSON
322,Jurisprudence_FR,JUR_FR_04.txt,CONSEIL,ORG
323,Jurisprudence_FR,JUR_FR_04.txt,ÉTAT,LOC
324,Jurisprudence_FR,JUR_FR_04.txt,XI-19.592,PERSON
325,Jurisprudence_FR,JUR_FR_04.txt,RÜTTER,LOC
326,Jurisprudence_FR,JUR_FR_04.txt,Roland,PERSON
327,Jurisprudence_FR,JUR_FR_04.txt,Me Th,PERSON
328,Jurisprudence_FR,JUR_FR_04.txt,FRANKIN,ORG
329,Jurisprudence_FR,JUR_FR_04.txt,Brugmann,PERSON
330,Jurisprudence_FR,JUR_FR_04.txt,Bruxelles,LOC
331,Jurisprudence_FR,JUR_FR_04.txt,Ministre de l'Intérieur,ORG
332,Jurisprudence_FR,JUR_FR_04.txt,Police fédérale,ORG
333,Jurisprudence_FR,JUR_FR_04.txt,Me B. RENSON,PERSON
334,Jurisprudence_FR,JUR_FR_04.txt,Père E. Devroye,PERSON
335,Jurisprudence_FR,JUR_FR_04.txt,XIe,LOC
336,Jurisprudence_FR,JUR_FR_04.txt,Roland RÜTTER,PERSON
337,Jurisprudence_FR,JUR_FR_04.txt,Conseil d’Etat,ORG
338,Jurisprudence_FR,JUR_FR_04.txt,Auditorat,LOC
339,Jurisprudence_FR,JUR_FR_04.txt,M. Ph,PERSON
340,Jurisprudence_FR,JUR_FR_04.txt,QUERTAINMONT,ORG
341,Jurisprudence_FR,JUR_FR_04.txt,président de Entendu,PERSON
342,Jurisprudence_FR,JUR_FR_04.txt,Me Thierry FRANKIN,PERSON
343,Jurisprudence_FR,JUR_FR_04.txt,Me Bernard RENSON,PERSON
344,Jurisprudence_FR,JUR_FR_04.txt,M. G. SCOHY,PERSON
345,Jurisprudence_FR,JUR_FR_04.txt,II,PERSON
346,Jurisprudence_FR,JUR_FR_04.txt,Conseil d'État,ORG
347,Jurisprudence_FR,JUR_FR_04.txt,Herstal,LOC
348,Jurisprudence_FR,JUR_FR_04.txt,Cour constitutionnelle,ORG
349,Jurisprudence_FR,JUR_FR_04.txt,Constitution,ORG
350,Jurisprudence_FR,JUR_FR_04.txt,Etat,LOC
351,Jurisprudence_FR,JUR_FR_04.txt,Ministre,ORG
352,Jurisprudence_FR,JUR_FR_04.txt,Cour de cassation,LOC
353,Jurisprudence_FR,JUR_FR_04.txt,Cour,LOC
354,Jurisprudence_FR,JUR_FR_04.txt,Conseil d’État,ORG
355,Jurisprudence_FR,JUR_FR_04.txt,Cour,ORG
356,Jurisprudence_FR,JUR_FR_04.txt,Cour constitutionnelle,LOC
357,Jurisprudence_FR,JUR_FR_04.txt,Mme C. DEBROUX,PERSON
358,Jurisprudence_FR,JUR_FR_04.txt,M. M. Y. HOUYET,PERSON
359,Jurisprudence_FR,JUR_FR_04.txt,X. DUPONT,PERSON
360,Jurisprudence_FR,JUR_FR_04.txt,Le Greffier,PERSON
361,Jurisprudence_FR,JUR_FR_04.txt,X. DUPONT conseiller d'Etat,PERSON
362,Jurisprudence_FR,JUR_FR_04.txt,Président,PERSON
363,Jurisprudence_FR,JUR_FR_04.txt,Ph,ORG
364,Jurisprudence_FR,JUR_FR_04.txt,QUERTAINMONT XI,PERSON
365,Jurisprudence_FR,JUR_FR_05.txt,CONSEIL,ORG
366,Jurisprudence_FR,JUR_FR_05.txt,ÉTAT,LOC
367,Jurisprudence_FR,JUR_FR_05.txt,SECTION,ORG
368,Jurisprudence_FR,JUR_FR_05.txt,R R Ê,LOC
369,Jurisprudence_FR,JUR_FR_05.txt,VAN DEN,ORG
370,Jurisprudence_FR,JUR_FR_05.txt,M e Jean BOURTEMBOURG,PERSON
371,Jurisprudence_FR,JUR_FR_05.txt,Suisse 24 1060 Bruxelles,LOC
372,Jurisprudence_FR,JUR_FR_05.txt,Charleroi,LOC
373,Jurisprudence_FR,JUR_FR_05.txt,M e Nathalie,ORG
374,Jurisprudence_FR,JUR_FR_05.txt,Jules Destrée 72 6001 Marcinelle,PERSON
375,Jurisprudence_FR,JUR_FR_05.txt,Annie VAN,PERSON
376,Jurisprudence_FR,JUR_FR_05.txt,Commission de sélection du 22 juin 2011,ORG
377,Jurisprudence_FR,JUR_FR_05.txt,TEC,ORG
378,Jurisprudence_FR,JUR_FR_05.txt,M.,PERSON
379,Jurisprudence_FR,JUR_FR_05.txt,Laurence LEJEUNE,PERSON
380,Jurisprudence_FR,JUR_FR_05.txt,Conseil d'État,ORG

In [10]:
stats_labels = ner_df["label"].value_counts().reset_index()
stats_labels.columns = ["label", "nombre"]

stats_labels

    label  nombre
0  PERSON     264
1     ORG     246
2     LOC     180

In [11]:
stats_par_corpus = pd.crosstab(
    ner_df["corpus"],
    ner_df["label"]
).reset_index()

stats_par_corpus

label            corpus  LOC  ORG  PERSON
0        HaveYourSay_EN   16   41      24
1        HaveYourSay_FR   31   13      18
2        HaveYourSay_NL    8   14       5
3      Jurisprudence_FR   57   76      95
4      Jurisprudence_NL   68  102     122

In [12]:
ner_df.to_excel("tableau_ner_complet.xlsx", index=False)
stats_labels.to_excel("statistiques_labels_ner.xlsx", index=False)
stats_par_corpus.to_excel("statistiques_ner_par_corpus.xlsx", index=False)